
# device setting "cuda", "cpu"
device: cuda

# federated learning
# users:            number of users
# random_sampling:   whether or not perform random sampling before each iteration
# sampling_fraction: the fraction of users to sample
# iid:              whether the data is iid or non-iid.
# labelsPerUser:    when data is assigned in a no-iid fashion.
users: 10
random_sampling: true
sampling_fraction: 1
iid: true
labelsPerUser: 1

# hyperparameters and model type
# model:        "naiveMLP", "naiveCNN"
local_batch_size: 1024
lr: 0
epoch: 40
model: "naiveCNN"

# compressors: signSGD, pred_rle_signSGD
# predictive: apply predictive encoding  
# take_turns: apply the trick of taking turns rto send "+" and "-"
# compressor:   "pred_rle_signSGD"
compressor:   "pred_signSGD"
predictive:   true
take_turns:   true
# compressor:   "signSGD"
# predictive:   false
# take_turns:    false

# Dataset configurations
# test_data_dir : the directory to the testDataset
# train_data_dir: the directory to the trainDataset
# sample_size:   the size of one sample [height x width/num_of_features]
# classes:      the class of the sample
record_dir:     ./record.dat
test_data_dir:  /media/kaiyue/7CF8DCC2F8DC7BB8/DataSets/MNIST/Pickle/test.dat
train_data_dir: /media/kaiyue/7CF8DCC2F8DC7BB8/DataSets/MNIST/Pickle/train.dat
sample_size:
- 28
- 28
classes: 10

# Log configurations
log_level:   "INFO"
log_file:    "./train.log"