
# device setting "cuda", "cpu"
device: cuda

# federated learning
# users:            number of users
# randomSampling:   whether or not perform random sampling before each iteration
# samplingFraction: the fraction of users to sample
# iid:              whether the data is iid or non-iid.
# labelsPerUser:    when data is assigned in a no-iid fashion.
users: 1
randomSampling: true
samplingFraction: 1
iid: true
labelsPerUser: 1


# hyperparameters and model type
# model:        "naiveMLP", "naiveCNN"
localBatchSize: 30000
lr: 0.1
epoch: 50
model: "naiveMLP"

# compressors: signSGD, pred_rle_signSGD
# predictive: apply predictive encoding  
# takeTurns: apply the trick of taking turns rto send "+" and "-"
# compressor:   "pred_rle_signSGD"
compressor:   "pred_signSGD"
predictive:   true
takeTurns:    true
# compressor:   "signSGD"
# predictive:   false
# takeTurns:    false

# Dataset configurations
# testDataDir : the directory to the testDataset
# trainDataDir: the directory to the trainDataset
# sampleSize:   the size of one sample [height x width/num_of_features]
# classes:      the class of the sample
testDataDir: /media/kaiyue/7CF8DCC2F8DC7BB8/DataSets/MNIST/Pickle/test.dat
trainDataDir: /media/kaiyue/7CF8DCC2F8DC7BB8/DataSets/MNIST/Pickle/train.dat
sampleSize:
- 28
- 28
classes: 10

# Log configurations
logLevel:   "INFO"
logFile:    "./train.log"